#ifndef INCLUDE_DVIFILE_H_
#define INCLUDE_DVIFILE_H_

#include <stdint.h>
#include <stdio.h>

#include <vector>

#include <Ancillary/ByteBuffer.h>
#include <Ancillary/ByteString.h>
#include <Ancillary/SmallVector.h>
#include <Ancillary/OwningPtr.h>


#include <Ancillary/CXXSupport.h>

namespace dviview {

typedef enum {
  Int1,
  Int2,
  Int3,
  Int4,
  String1,
  BString1,
  BString2,
  BString3,
  BString4,
  SumString,
  NullOperand, // to terminate the operand string.
} DVIOperandType;

typedef struct {
    char name[16];
    DVIOperandType operands[12];
} DVIOperationDefinition;


class DVIOperation {
  public:
    typedef union {
      int32_t integer;
      ByteString *string;
    } Operand;
  private: 
    uint8_t opcode;
    SmallVector<Operand, 10> operands;
  public:
    DVIOperation() : opcode(138) /* NOP */, operands(SmallVector<Operand, 10>()) {}
    DVIOperation(uint8_t opcode, SmallVector<Operand, 10> operands) : opcode(opcode), operands(operands) {}
    uint8_t getOpcode() {return opcode;}
    SmallVector<Operand, 10> getOperands() {return operands;}
};

class DVIFileParser {
  private:
    DISALLOW_COPY_AND_ASSIGN(DVIFileParser);
    uint64_t index;
    std::vector<DVIOperation> ops;
  public:
    DVIFileParser() : index(0), ops(std::vector<DVIOperation>()) {}
    int parse(ByteBuffer &buf);
    std::vector<DVIOperation> operations() {return ops;}
  private:
    int readOperand(ByteBuffer &buffer, DVIOperation::Operand &operand, DVIOperandType type);
    int readOperation(ByteBuffer &buffer, DVIOperation &operation);
};

static const DVIOperationDefinition dviOPTable[256] = {
{"set_char_0", {NullOperand}},
{"set_char_1", {NullOperand}},
{"set_char_2", {NullOperand}},
{"set_char_3", {NullOperand}},
{"set_char_4", {NullOperand}},
{"set_char_5", {NullOperand}},
{"set_char_6", {NullOperand}},
{"set_char_7", {NullOperand}},
{"set_char_8", {NullOperand}},
{"set_char_9", {NullOperand}},
{"set_char_10", {NullOperand}},
{"set_char_11", {NullOperand}},
{"set_char_12", {NullOperand}},
{"set_char_13", {NullOperand}},
{"set_char_14", {NullOperand}},
{"set_char_15", {NullOperand}},
{"set_char_16", {NullOperand}},
{"set_char_17", {NullOperand}},
{"set_char_18", {NullOperand}},
{"set_char_19", {NullOperand}},
{"set_char_20", {NullOperand}},
{"set_char_21", {NullOperand}},
{"set_char_22", {NullOperand}},
{"set_char_23", {NullOperand}},
{"set_char_24", {NullOperand}},
{"set_char_25", {NullOperand}},
{"set_char_26", {NullOperand}},
{"set_char_27", {NullOperand}},
{"set_char_28", {NullOperand}},
{"set_char_29", {NullOperand}},
{"set_char_30", {NullOperand}},
{"set_char_31", {NullOperand}},
{"set_char_32", {NullOperand}},
{"set_char_!", {NullOperand}},
{"set_char_\"", {NullOperand}},
{"set_char_#", {NullOperand}},
{"set_char_$", {NullOperand}},
{"set_char_%", {NullOperand}},
{"set_char_&", {NullOperand}},
{"set_char_'", {NullOperand}},
{"set_char_(", {NullOperand}},
{"set_char_)", {NullOperand}},
{"set_char_*", {NullOperand}},
{"set_char_+", {NullOperand}},
{"set_char_,", {NullOperand}},
{"set_char_-", {NullOperand}},
{"set_char_.", {NullOperand}},
{"set_char_/", {NullOperand}},
{"set_char_0", {NullOperand}},
{"set_char_1", {NullOperand}},
{"set_char_2", {NullOperand}},
{"set_char_3", {NullOperand}},
{"set_char_4", {NullOperand}},
{"set_char_5", {NullOperand}},
{"set_char_6", {NullOperand}},
{"set_char_7", {NullOperand}},
{"set_char_8", {NullOperand}},
{"set_char_9", {NullOperand}},
{"set_char_:", {NullOperand}},
{"set_char_;", {NullOperand}},
{"set_char_<", {NullOperand}},
{"set_char_=", {NullOperand}},
{"set_char_>", {NullOperand}},
{"set_char_?", {NullOperand}},
{"set_char_@", {NullOperand}},
{"set_char_A", {NullOperand}},
{"set_char_B", {NullOperand}},
{"set_char_C", {NullOperand}},
{"set_char_D", {NullOperand}},
{"set_char_E", {NullOperand}},
{"set_char_F", {NullOperand}},
{"set_char_G", {NullOperand}},
{"set_char_H", {NullOperand}},
{"set_char_I", {NullOperand}},
{"set_char_J", {NullOperand}},
{"set_char_K", {NullOperand}},
{"set_char_L", {NullOperand}},
{"set_char_M", {NullOperand}},
{"set_char_N", {NullOperand}},
{"set_char_O", {NullOperand}},
{"set_char_P", {NullOperand}},
{"set_char_Q", {NullOperand}},
{"set_char_R", {NullOperand}},
{"set_char_S", {NullOperand}},
{"set_char_T", {NullOperand}},
{"set_char_U", {NullOperand}},
{"set_char_V", {NullOperand}},
{"set_char_W", {NullOperand}},
{"set_char_X", {NullOperand}},
{"set_char_Y", {NullOperand}},
{"set_char_Z", {NullOperand}},
{"set_char_[", {NullOperand}},
{"set_char_\\", {NullOperand}},
{"set_char_]", {NullOperand}},
{"set_char_^", {NullOperand}},
{"set_char__", {NullOperand}},
{"set_char_`", {NullOperand}},
{"set_char_a", {NullOperand}},
{"set_char_b", {NullOperand}},
{"set_char_c", {NullOperand}},
{"set_char_d", {NullOperand}},
{"set_char_e", {NullOperand}},
{"set_char_f", {NullOperand}},
{"set_char_g", {NullOperand}},
{"set_char_h", {NullOperand}},
{"set_char_i", {NullOperand}},
{"set_char_j", {NullOperand}},
{"set_char_k", {NullOperand}},
{"set_char_l", {NullOperand}},
{"set_char_m", {NullOperand}},
{"set_char_n", {NullOperand}},
{"set_char_o", {NullOperand}},
{"set_char_p", {NullOperand}},
{"set_char_q", {NullOperand}},
{"set_char_r", {NullOperand}},
{"set_char_s", {NullOperand}},
{"set_char_t", {NullOperand}},
{"set_char_u", {NullOperand}},
{"set_char_v", {NullOperand}},
{"set_char_w", {NullOperand}},
{"set_char_x", {NullOperand}},
{"set_char_y", {NullOperand}},
{"set_char_z", {NullOperand}},
{"set_char_{", {NullOperand}},
{"set_char_|", {NullOperand}},
{"set_char_}", {NullOperand}},
{"set_char_~", {NullOperand}},
{"set_char_127", {NullOperand}},
{"set1", {Int1, NullOperand}},
{"set2", {Int2, NullOperand}},
{"set3", {Int3, NullOperand}},
{"set4", {Int4, NullOperand}},
{"set_rule", {Int4, Int4, NullOperand}},
{"put1", {Int1, NullOperand}},
{"put2", {Int2, NullOperand}},
{"put3", {Int3, NullOperand}},
{"put4", {Int4, NullOperand}},
{"put_rule", {Int4, Int4, NullOperand}},
{"nop", {NullOperand}},
{"bop", {Int4, Int4, Int4, Int4, Int4, Int4, Int4, Int4, Int4, Int4, Int4, NullOperand}},
{"eop", {NullOperand}},
{"push", {NullOperand}},
{"pop", {NullOperand}},
{"right1", {Int1, NullOperand}},
{"right2", {Int2, NullOperand}},
{"right3", {Int3, NullOperand}},
{"right4", {Int4, NullOperand}},
{"w0", {NullOperand}},
{"w1", {Int1, NullOperand}},
{"w2", {Int2, NullOperand}},
{"w3", {Int3, NullOperand}},
{"w4", {Int4, NullOperand}},
{"x0", {NullOperand}},
{"x1", {Int1, NullOperand}},
{"x2", {Int2, NullOperand}},
{"x3", {Int3, NullOperand}},
{"x4", {Int4, NullOperand}},
{"down1", {Int1, NullOperand}},
{"down2", {Int2, NullOperand}},
{"down3", {Int3, NullOperand}},
{"down4", {Int4, NullOperand}},
{"y0", {NullOperand}},
{"y1", {Int1, NullOperand}},
{"y2", {Int2, NullOperand}},
{"y3", {Int3, NullOperand}},
{"y4", {Int4, NullOperand}},
{"z0", {NullOperand}},
{"z1", {Int1, NullOperand}},
{"z2", {Int2, NullOperand}},
{"z3", {Int3, NullOperand}},
{"z4", {Int4, NullOperand}},
{"fnt_num_171", {NullOperand}},
{"fnt_num_172", {NullOperand}},
{"fnt_num_173", {NullOperand}},
{"fnt_num_174", {NullOperand}},
{"fnt_num_175", {NullOperand}},
{"fnt_num_176", {NullOperand}},
{"fnt_num_177", {NullOperand}},
{"fnt_num_178", {NullOperand}},
{"fnt_num_179", {NullOperand}},
{"fnt_num_180", {NullOperand}},
{"fnt_num_181", {NullOperand}},
{"fnt_num_182", {NullOperand}},
{"fnt_num_183", {NullOperand}},
{"fnt_num_184", {NullOperand}},
{"fnt_num_185", {NullOperand}},
{"fnt_num_186", {NullOperand}},
{"fnt_num_187", {NullOperand}},
{"fnt_num_188", {NullOperand}},
{"fnt_num_189", {NullOperand}},
{"fnt_num_190", {NullOperand}},
{"fnt_num_191", {NullOperand}},
{"fnt_num_192", {NullOperand}},
{"fnt_num_193", {NullOperand}},
{"fnt_num_194", {NullOperand}},
{"fnt_num_195", {NullOperand}},
{"fnt_num_196", {NullOperand}},
{"fnt_num_197", {NullOperand}},
{"fnt_num_198", {NullOperand}},
{"fnt_num_199", {NullOperand}},
{"fnt_num_200", {NullOperand}},
{"fnt_num_201", {NullOperand}},
{"fnt_num_202", {NullOperand}},
{"fnt_num_203", {NullOperand}},
{"fnt_num_204", {NullOperand}},
{"fnt_num_205", {NullOperand}},
{"fnt_num_206", {NullOperand}},
{"fnt_num_207", {NullOperand}},
{"fnt_num_208", {NullOperand}},
{"fnt_num_209", {NullOperand}},
{"fnt_num_210", {NullOperand}},
{"fnt_num_211", {NullOperand}},
{"fnt_num_212", {NullOperand}},
{"fnt_num_213", {NullOperand}},
{"fnt_num_214", {NullOperand}},
{"fnt_num_215", {NullOperand}},
{"fnt_num_216", {NullOperand}},
{"fnt_num_217", {NullOperand}},
{"fnt_num_218", {NullOperand}},
{"fnt_num_219", {NullOperand}},
{"fnt_num_220", {NullOperand}},
{"fnt_num_221", {NullOperand}},
{"fnt_num_222", {NullOperand}},
{"fnt_num_223", {NullOperand}},
{"fnt_num_224", {NullOperand}},
{"fnt_num_225", {NullOperand}},
{"fnt_num_226", {NullOperand}},
{"fnt_num_227", {NullOperand}},
{"fnt_num_228", {NullOperand}},
{"fnt_num_229", {NullOperand}},
{"fnt_num_230", {NullOperand}},
{"fnt_num_231", {NullOperand}},
{"fnt_num_232", {NullOperand}},
{"fnt_num_233", {NullOperand}},
{"fnt_num_234", {NullOperand}},
{"fnt1", {Int1, NullOperand}},
{"fnt2", {Int2, NullOperand}},
{"fnt3", {Int3, NullOperand}},
{"fnt4", {Int4, NullOperand}},
{"xxx1", {BString1, NullOperand}},
{"xxx2", {BString2, NullOperand}},
{"xxx3", {BString3, NullOperand}},
{"xxx4", {BString4, NullOperand}},
{"fnt_def1", {Int1, Int4, Int4, Int4, SumString, NullOperand}},
{"fnt_def2", {Int2, Int4, Int4, Int4, SumString, NullOperand}},
{"fnt_def3", {Int3, Int4, Int4, Int4, SumString, NullOperand}},
{"fnt_def4", {Int4, Int4, Int4, Int4, SumString, NullOperand}},
{"pre", {Int1, Int4, Int4, Int4, String1, NullOperand}},
{"post", {Int4, Int4, Int4, Int4, Int4, Int4, Int2, Int2, NullOperand}},
{"post_post", {Int4, Int1, NullOperand}},
{"UNDEFINED_250", {NullOperand}},
{"UNDEFINED_251", {NullOperand}},
{"UNDEFINED_252", {NullOperand}},
{"UNDEFINED_253", {NullOperand}},
{"UNDEFINED_254", {NullOperand}},
{"UNDEFINED_255", {NullOperand}},
};

} // namespace dviview

#endif  // INCLUDE_DVIFILE_H_
